### ISSUE TITLE
exporter is not exporting metrics...

### ISSUE THREAD

**Issue by meierale** [tiagoReichert/otc-cloudeye-prometheus-exporter#1]
Hi there
I'm facing an issue with the exporter, but I'm not really sure whether it is an exporter issue... or actually an issue with either OTC or my permissions. I hope the explanation below is clear enough:

- I managed to get the exporter up and running in an openshift environment 
- From this openshift environment I can access multiple tenants on OTC
- Whilst I can get the exporter to expose metrics on tenant A, I can not get it to export metrics for tenant B
- for tenant B, when I look at the logs of the exporter, it is full of lines containing '...(get_ecs_mapping): Created name entry for ECS...' so ECS mapping works.
- But there are no metrics being logged which explains why they are not exposed to prometheus

Any ideas what could be the cause? The users I use to access Tenant A and B have the same rights in OTC. Both are members of a dedicated 'monitoring' user group that has the following policy for the projects in question: "Guest, CES Administrator".

Thanks :-)

**Comment by tiagoReichert** [comment]
Hi,

I doubt that the problem is related to your IAM permissions, it should work just with `BASE->Tenant Guest` permission, I don't even have here the `CES Administrator` role added to the user group. And as you already stated, it works on the other tenant with the same permissions.

Unfortunately, there is an OTC CES API limitation that allows only 140 requests per minute and the API does not support bulk requests (the exporter has to do one request against the API per metric that it tries to get). This is already addressed with the OTC team and I hope that they release soon such a feature to make bulk requests against the CES API. Taking this into consideration if you are trying to get more the 140 metrics (for example, 10 metrics per ECS multiplied by 14 ECS would already reach the maximum allowed by OTC) you will probably face some issues (like some metrics being exposed by the exporter and some not)

For further analysis please do the following test:
Run a curl against the exporter to see if it is really not exposing any metric:
 `curl http://localhost:8000`
If you are using the container provided you can easily install curl with:
`apk add curl`

Please also inform around how many resources you are monitoring on tenant A and tenant B and if you are using only the main project or sub-projects. This will help me to simulate your problem.

**Comment by meierale** [comment]
Hi Tiago
Sorry for the late response! 
As I'm using your exporter in an Openshift Cluster it is a bit more tricky, as in that specific setup I can not simply install curl on the pod. But i could build a new docker image with curl installed (if necessary).
Regarding the amount of resources in tenant A and B and main or sub-projects:

- in tenant A (working) all instances are created in the main project and there are a total of 22 ECS instances with ~50 disks attached to them
- in tenant B (not working) all instances we're interested in are in a sub-project (PROJECT_ID variable is set to the sub-project id) and there are a total of 38 ECS instances (but with ~270 disks attached to the ecs instances)

**Comment by tiagoReichert** [comment]
It seems you reached an API requests limit from OTC. I already tried to contact the support team asking to implement some kind of bulk request. However, without any positive response.
If you are able to contact them too, try to ask them too. Maybe with more people requesting for it, they might implement such functionality. 

About the limitation:  https://github.com/tiagoReichert/otc-cloudeye-prometheus-exporter#known-limitations

**Comment by Mel3VeN** [comment]
Hey,

sorry to revive this now, but I'm running into the exact same issue.

When Using the Main Project, the ECS metrics get exported correctly, but in the Sub-Project, I get no metrics at all.

I understand the API limit, but it should still get metrics up until it reaches that limit.

From logs it seems like the "get_metric_value" function is not triggered at all, when using a sub project.

All I get is:

`(get_ecs_mapping) Created name entry for ECS xxx successfully`
`(get_ecs_mapping) Created name entry for ECS xxx successfully`
`(get_ecs_mapping) Created name entry for ECS xxx successfully`
`(get_ecs_mapping) Created name entry for ECS xxx successfully`
`(save_config_file): Configuration file successfully saved`

So there 0 metrics exported, even though all Instances are recognized correctly.

When using the main project ID, the get_metric_value function is triggered.

Did anyone figure out what causes this issue?
